<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Mobile app Automation" duration-ms="39841" started-at="2020-05-09T13:28:36Z" finished-at="2020-05-09T13:29:16Z">
    <groups>
    </groups>
    <test name="Amazon App" duration-ms="39841" started-at="2020-05-09T13:28:36Z" finished-at="2020-05-09T13:29:16Z">
      <class name="com.amazon.tests.PurchaseItem">
        <test-method status="PASS" signature="initializeDriver(java.lang.String)[pri:0, instance:com.amazon.tests.PurchaseItem@2aece37d]" name="initializeDriver" is-config="true" duration-ms="17340" started-at="2020-05-09T13:28:36Z" finished-at="2020-05-09T13:28:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[RealAndroidDevice]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeDriver -->
        <test-method status="FAIL" signature="purchaseItem()[pri:0, instance:com.amazon.tests.PurchaseItem@2aece37d]" name="purchaseItem" duration-ms="21339" started-at="2020-05-09T13:28:53Z" finished-at="2020-05-09T13:29:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to get product priceString index out of range: -2]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to get product priceString index out of range: -2
at org.testng.Assert.fail(Assert.java:96)
at com.amazon.pages.AmazonSelectedProductPage.productPriceOnProductPage(AmazonSelectedProductPage.java:82)
at com.amazon.tests.PurchaseItem.purchaseItem(PurchaseItem.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- purchaseItem -->
        <test-method status="PASS" signature="quitDriver()[pri:0, instance:com.amazon.tests.PurchaseItem@2aece37d]" name="quitDriver" is-config="true" duration-ms="1058" started-at="2020-05-09T13:29:15Z" finished-at="2020-05-09T13:29:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- com.amazon.tests.PurchaseItem -->
    </test> <!-- Amazon App -->
  </suite> <!-- Mobile app Automation -->
</testng-results>
